---
version: "3.7"

services:
  ocis:
    environment:
      # tracing
      OCIS_TRACING_ENABLED: "true"
      OCIS_TRACING_TYPE: "jaeger"
      OCIS_TRACING_ENDPOINT: jaeger-agent:6831
      # metrics
      PROXY_DEBUG_ADDR: 0.0.0.0:9205
  collaboration:
    environment:
      # tracing
      OCIS_TRACING_ENABLED: "true"
      OCIS_TRACING_TYPE: "jaeger"
      OCIS_TRACING_ENDPOINT: jaeger-agent:6831
      # metrics
      COLLABORATION_DEBUG_ADDR: 0.0.0.0:9304

networks:
  ocis-net:
    external: true
